### PR TITLE
Adding Power Analysis

### PR DESCRIPTION
**Pull request by gwaygenomics**
How many morphological profiles are required to detect significant differences between wild-type and resistant clones?

I add a power analysis to determine appropriate sample size here:

## Results

power_analysis

The dotted blue line is currently how many samples we have in the pilot study (~50 per condition). There are 185 transparent lines in this figure representing the effect sizes _of each feature_ actually observed in the pilot data. In other words, some features have very large differences, others don't. The red line indicates the mean and +/- standard error of the mean for all feature differences. Alpha is adjusted for multiple test corrections (0.05 / 185)

The tested n's include c(10, 25, 50, 75, 100, 250, 500, 750, 1000, 2000, 5000, 10000).

## Conclusion

To have reasonable power to detect true differences between comparisons in features with reasonable effect sizes, I recommend collecting somewhere between 250 and 1,000 profiles per condition (green shaded region).

Does this sound reasonable @shntnu @AnneCarpenter? Is this what we've typically seen in the past? Should I be thinking about this analysis differently? Thanks!

### CODE REVIEW

**Comment by shntnu** [comment]
@gwaygenomics If the goal is as statue – to find how many morphological profiles are required to detect significant differences between wild-type and resistant clones – then I'm not a univariate analysis is useful direction. But first – is that indeed the goal?

**Comment by gwaygenomics** [comment]
> to find how many morphological profiles are required to detect significant differences between wild-type and resistant clones

Yep, this is one goal. The primary goal that motivates this analysis is to determine how many more samples we need to collect.

> then I'm not sure that a univariate analysis is a useful direction

We're currently in pilot phases of performing relatively simple comparisons between groups. One goal of the study is to identify the most distinct morphology features between these groups. My thought is that the analysis above will tell us how many profiles we need to identify significant differences with effect sizes we've observed in practice. The alpha in the power analysis is bonferronni adjusted too.

**Comment by shntnu** [comment]
> We're currently in pilot phases of performing relatively simple comparisons between groups. One goal of the study is to identify the most distinct morphology features between these groups. My thought is that the analysis above will tell us how many profiles we need to identify significant differences with effect sizes we've observed in practice. The alpha in the power analysis is bonferronni adjusted too.

Got it - I missed out on the implication of the correction.

I'll ponder this, but just a few questions

- How are you determining effect size? I saw the code but didn't quite get the rationale of estimating that from the data
- you have `alpha <- 0.5 / length(cp_features)` – is that supposed to be `0.05`?
- How are you arriving at the band of 250-1000? Is it based on the red curve (mean)?

**Comment by gwaygenomics** [comment]
> you have alpha <- 0.5 / length(cp_features) – did you intend that to be 0.05 / length(cp_features)?

Amazing find!!! Updated in 8cc90ae0e160240651444dd85750a2fa9ad4f4f4

> How are you determining effect size? I saw the code but didn't quite get the rationale of estimating that from the data

Effect size is estimated using real data and [cohen's d](https://en.wikipedia.org/wiki/Effect_size#Cohen's_d) (see [here](https://github.com/broadinstitute/profiling-resistance-mechanisms/pull/29/commits/d98158b9c8ea4645aff2794c8f568c2fb59f32c4#diff-bbad798e35e249215fa608fdb70ea057R5)).

So i take wt clones and mutant clones as the two groups and observe effect size for all features

> How are you arriving at the band of 250-1000? Is it based on the red curve (mean)?

Note it is now 500 after updating alpha. This is based on my 👀 . I like that a lot of features have power = 100 at these sample sizes. So i'd be confident that we'd find real differences for ranges of effect sizes with these sample sizes. I'm sure there is a better way to do this...

**Comment by shntnu** [comment]
For our notes – Greg and I chatted and discussed strategies. Related papers:
- http://cbcl.mit.edu/publications/ps/sample_size.pdf
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3307431/
- https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-447

**Comment by AnneCarpenter** [comment]
Sorry I'm just catching up on github notifications, can you clarify what you mean by 'sample' here? One could in theory mean:
1 single-cell profiles (or trajectories over time)
2 single-cell averaged profiles of a particular technical replicate of a given resistant or sensitive clone
3 replicate-averaged profiles of single-cell averaged profiles of a given resistant or sensitive clone

It's easiest to get lots of (1), harder to get (2), and way hard to get (3). If (3) then I think hundreds is completely out of the question, unfortunately, but I think the main factor here is what effect size we expect/hope to see.

**Comment by gwaygenomics** [comment]
abandoning power analysis idea - not pursuing for now

**Pull request closed without merging**
